namespace MgaWwiseIMImporter.Domain;

internal static partial class UiStrings
{
    // --- ColorDev panel ---
    public static string ColorDevTitle => Get("色調整（開発者）", "Color Adjustment (Developer)");
    public static string ColorDevClose => Get("閉じる", "Close");
    public static string ColorDevResetToDefaults => Get("既定に戻す", "Reset to Defaults");

    /// <summary>色調整パネルの表示名（キー → 日英ラベル）。<see cref="UiColors.Entries"/> の Key と対応。</summary>
    public static string ColorLabel(string key) => key switch
    {
        "PrimaryFore" => Get("共通・標準文字／アイコン", "Common - Primary Text / Icon"),
        "MutedFore" => Get("共通・弱い文字／枠", "Common - Muted Text / Border"),
        "AccentCyan" => Get("共通・シアンアクセント", "Common - Cyan Accent"),
        "SurfaceBack" => Get("共通・基本背景", "Common - Base Background"),
        "ChromeBack" => Get("共通・クローム背景", "Common - Chrome Background"),
        "ChromeBorder" => Get("共通・クローム境界線／ホバー", "Common - Chrome Border / Hover"),
        "ChromeMid" => Get("共通・中間グレー（押下／つまみ）", "Common - Mid Gray (Pressed / Thumb)"),
        "ChromeDim" => Get("共通・やや明るいグレー（無効／ホバー）", "Common - Dim Gray (Disabled / Hover)"),
        "WaveformBack" => Get("波形エリア背景", "Waveform Area Background"),
        "EmptyHint" => Get("空状態ヒント", "Empty State Hint"),
        "TempoBg" => Get("テンポ・背景", "Tempo - Background"),
        "SignatureBg" => Get("拍子・背景", "Signature - Background"),
        "MarkerRowBg" => Get("マーカー行・背景", "Marker Row - Background"),
        "MarkerTriangle" => Get("マーカー三角", "Marker Triangle"),
        "BarLine" => Get("小節線", "Bar Line"),
        "BeatLine" => Get("拍線", "Beat Line"),
        "TempoChangeLine" => Get("テンポ変更線", "Tempo Change Line"),
        "WaveFill" => Get("波形", "Waveform Fill"),
        "WaveZeroDbLine" => Get("波形 0dB 線", "Waveform 0 dB Line"),
        "WaveformSourceMeterTrack" => Get("波形メーター・トラック", "Waveform Meter - Track"),
        "WaveformSourceMeterMinimum" => Get("波形メーター・最小", "Waveform Meter - Minimum"),
        "WaveformSourceMeterMaximum" => Get("波形メーター・最大", "Waveform Meter - Maximum"),
        "RegionWaveFillGray" => Get("波形リージョン塗り（通常）", "Region Fill (Normal)"),
        "RegionWaveFillExcluded" => Get("波形リージョン塗り（-R）", "Region Fill (-R)"),
        "RegionWaveFillLoop" => Get("波形リージョン塗り（-L）", "Region Fill (-L)"),
        "RegionWaveFillAnacrusis" => Get("波形リージョン塗り（-A）", "Region Fill (-A)"),
        "RegionWaveFillExit" => Get("波形リージョン塗り（-E）", "Region Fill (-E)"),
        "RegionBoundaryMarker" => Get("リージョン境界マーカー", "Region Boundary Marker"),
        "EntryCueMarker" => Get("Entry Cue マーカー", "Entry Cue Marker"),
        "ExitCueMarker" => Get("Exit Cue マーカー", "Exit Cue Marker"),
        "RegionFadeCurve" => Get("リージョン端フェード曲線", "Region Edge Fade Curve"),
        "OutputPartShadow" => Get("出力パート名・影", "Output Part Name - Shadow"),
        "MusicSegmentLaneBg" => Get("Music Segment Name・背景", "Music Segment Name - Background"),
        "MusicPlaylistLaneBg" => Get("Music Playlist Name・背景", "Music Playlist Name - Background"),
        "SeekExit" => Get("Exit 二重再生ヘッド", "Exit Dual Playhead"),
        "SeekAnacrusis" => Get("アウフタクト先行再生ヘッド", "Anacrusis Lead-in Playhead"),
        "SeekFadeOut" => Get("遷移元フェードアウトヘッド", "Source Fade-out Playhead"),
        "MouseGuide" => Get("マウスガイド", "Mouse Guide"),
        "WaveformScrollTrack" => Get("波形スクロール・トラック", "Waveform Scrollbar - Track"),
        "TransportBadgeBack" => Get("Transport・ズーム記号背景", "Transport - Zoom Badge Background"),
        "LogDefault" => Get("ログ文字（既定）", "Log Text (Default)"),
        "LogHeader" => Get("ログ文字（ヘッダ）", "Log Text (Header)"),
        "LogWarning" => Get("ログ文字（警告）", "Log Text (Warning)"),
        "LogError" => Get("ログ文字（エラー）", "Log Text (Error)"),
        "OptionGlyphCheckMark" => Get("オプション・チェック線", "Option - Check Mark"),
        "SectionHeaderBack" => Get("セクション見出し・背景", "Section Header - Background"),
        "PlaylistAutoBack" => Get("Playlist・自動再生開始フェード塗り", "Playlist - Auto Start Fade Fill"),
        "PlaylistManualBack" => Get("Playlist・手動再生開始フェード塗り", "Playlist - Manual Start Fade Fill"),
        "PlaylistManualBorder" => Get("Playlist・手動再生中枠", "Playlist - Manual Playing Border"),
        "MarkerCommentErrorFore" => Get("Marker Comment・エラー文字", "Marker Comment - Error Text"),
        "ActionLinkFore" => Get("Action Bar・リンク文字", "Action Bar - Link Text"),
        "ReloadButtonFill" => Get("RELOAD・塗り", "RELOAD - Fill"),
        "ReloadButtonHoverFill" => Get("RELOAD・ホバー塗り", "RELOAD - Hover Fill"),
        "ReloadButtonBack" => Get("RELOAD・枠", "RELOAD - Border"),
        "ReloadButtonHoverBack" => Get("RELOAD・ホバー枠", "RELOAD - Hover Border"),
        "ReloadButtonPressedBack" => Get("RELOAD・押下枠", "RELOAD - Pressed Border"),
        "ClearButtonFill" => Get("CLEAR・塗り", "CLEAR - Fill"),
        "ClearButtonHoverFill" => Get("CLEAR・ホバー塗り", "CLEAR - Hover Fill"),
        "ClearButtonBack" => Get("CLEAR・枠", "CLEAR - Border"),
        "ClearButtonHoverBack" => Get("CLEAR・ホバー枠", "CLEAR - Hover Border"),
        "ClearButtonPressedBack" => Get("CLEAR・押下枠", "CLEAR - Pressed Border"),
        "ExportButtonFill" => Get("EXPORT・塗り", "EXPORT - Fill"),
        "ExportButtonHoverFill" => Get("EXPORT・ホバー塗り", "EXPORT - Hover Fill"),
        "ExportButtonBack" => Get("EXPORT・枠", "EXPORT - Border"),
        "ExportButtonHoverBack" => Get("EXPORT・ホバー枠", "EXPORT - Hover Border"),
        "ExportButtonPressedBack" => Get("EXPORT・押下枠", "EXPORT - Pressed Border"),
        "SpectrumBar" => Get("スペアナ・バー", "Spectrum - Bar"),
        "StatusBarBack" => Get("WAAPI Status・背景", "WAAPI Status - Background"),
        "StatusBarConnectedBadgeBack" => Get("WAAPI Status・接続バッジ背景", "WAAPI Status - Connected Badge Background"),
        "StatusBarDisconnectedBadgeBack" => Get(
            "WAAPI Status・切断バッジ背景",
            "WAAPI Status - Disconnected Badge Background"),
        "StatusBarErrorDetailFore" => Get("WAAPI Status・エラー詳細文字", "WAAPI Status - Error Detail Text"),
        "KeepTargetLockFore" => Get("Keep Target・施錠", "Keep Target - Locked"),
        "KeepTargetLockHoverFore" => Get("Keep Target・施錠ホバー", "Keep Target - Locked Hover"),
        "KeepTargetUnlockFore" => Get("Keep Target・開錠", "Keep Target - Unlocked"),
        "KeepTargetUnlockHoverFore" => Get("Keep Target・開錠ホバー", "Keep Target - Unlocked Hover"),
        "TitleBarBack" => Get("タイトルバー・背景", "Title Bar - Background"),
        "DialogBodyBack" => Get("Go To Measure・背景", "Go To Measure - Background"),
        "DialogInputBack" => Get("Go To Measure・入力背景", "Go To Measure - Input Background"),
        "DialogShadow" => Get("Go To Measure・影", "Go To Measure - Shadow"),
        "ColorPanelBack" => Get("色設定パネル・背景", "Color Panel - Background"),
        "ColorPanelListBack" => Get("色設定パネル・一覧背景", "Color Panel - List Background"),
        "ColorPanelInputBack" => Get("色設定パネル・入力背景", "Color Panel - Input Background"),
        _ => key,
    };
}
